stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "rental-frontend"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_VERIFY: ""
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  tags:
    - fsa-poiasnik
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - until docker info &>/dev/null; do sleep 2 && echo "Waiting for Docker daemon..."; done
    - export IMAGE_VERSION="${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "https://$ACR_REGISTRY"
    - docker build -t "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION" -t "$ACR_REGISTRY/$IMAGE_NAME:latest" .
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION"
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:latest"
  only:
    - main

deploy:
  stage: deploy
  tags:
    - fsa-poiasnik
  image: alpine/k8s:1.32.3
  before_script:
    - apk add --no-cache git
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
  script:
    - git clone "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_NAMESPACE}/FSA-INFRA.git" infra
    - kubectl apply -f infra/kubernetes/workload/04-app-frontend/
    - kubectl apply -f infra/kubernetes/workload/05-ingress/app-ingress.yaml
    - kubectl set image deployment/fsa-fe fsa-fe="$ACR_REGISTRY/$IMAGE_NAME:latest" -n app
    - kubectl rollout restart deployment/fsa-fe -n app
    - kubectl rollout status deployment/fsa-fe -n app --timeout=240s
  only:
    - main
